# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Files
version:      0.12
version_from: Files.pm
installdirs:  site
requires:
    Algorithm::Diff:               0
    Test::Builder:                 0
    Test::Builder::Tester:         0
    Test::More:                    0
    Text::Diff:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
